// export const ON_IMAGE_SLIDER_START = "ON_IMAGE_SLIDER_START";
export const ON_IMAGE_POS_SUCCESS = "ON_IMAGE_SLIDER_SUCCESS";
export const ON_IMAGE_POS_FAIL = "ON_IMAGE_SLIDER_FAIL";

export const ON_IMAGE_OFF_SUCCESS = "ON_IMAGE_OFF_SUCCESS";
export const ON_IMAGE_OFF_FAIL = "ON_IMAGE_OFF_FAIL";
